version: '3'
services:
  server-wallet:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TERM: xterm
    volumes:
      - datavolume:/var/www/draftcoin
    ports:
      - "20304:20304"
volumes:
  datavolume: {}
